flutter:
  uses-material-design: true
  
  assets:
    - assets/branding/ala_logo.png
    - assets/branding/ala_app_icon.png  # Make sure this exists

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/ala_app_icon.png"  # Changed here!
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/branding/ala_app_icon.png"  # Changed here!
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/branding/ala_app_icon.png"  # Changed here!
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/branding/ala_app_icon.png"  # Changed here!
